--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Todo56/ShopUI
branches:
- master
projects:
  ShopUI:
    path: ""
    excludeDirs:
    - "resources/github"
    libs:
    - src: todoe56/shopui/libs/muqsit/invmenu/InvMenu
      version: ^2.1.0
...
