--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Todo56/ShopUI
branches:
- master
projects:
  ShopUI:
    path: ""
    excludeDirs:
    - "resources/github"
    icon: "ShopUI.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^2.1.0
...
